Packaging changes for 0.5 deb (make it build from our packager)

diff --git a/bin/herk_stash b/bin/herk_stash
--- a/bin/herk_stash
+++ b/bin/herk_stash
@@ -1,5 +1,5 @@
 #!/bin/bash
-# this script gets activated via a cron to sequentially cleanup riak nodes 
+# this script gets activated via a cron to sequentially cleanup riak nodes
 # when it receives a message to do so.
 #
 # Megam.  http://www.gomegam.com
@@ -7,42 +7,34 @@
 # Copyright 2014, Megam systems
 #
 
-MEGAM_AKKA_HOME_DIR=$(dirname $0)/../
-echo $MEGAM_AKKA_HOME_DIR >> /var/log/upstart/herk.log
+MEGAMD_HOME_DIR=/var/lib/megam/megamd
+MEGAMD_HOME_DIR=$(pushd $MEGAMD_HOME_DIR > /dev/null && echo $PWD && popd > /dev/null)
+MEGAMD_LOGS_DIR=$MEGAMD_HOME_DIR/logs
 
-MEGAM_AKKA_HOME_DIR=$(pushd $MEGAM_AKKA_HOME_DIR > /dev/null && echo $PWD && popd > /dev/null)
-echo $MEGAM_AKKA_HOME_DIR >> /var/log/upstart/herk.log
-
-
-MEGAM_AKKA_CONF_DIR=$MEGAM_AKKA_HOME_DIR/.megam
-MEGAM_AKKA_LOGS_DIR=$MEGAM_AKKA_HOME_DIR/logs
-echo $MEGAM_AKKA_CONF_DIR >> /var/log/upstart/herk.log
 # here it records all the stash messages made through the interface
-riakstash_file=$MEGAM_AKKA_CONF_DIR/riakstash
-
-echo $MEGAM_AKKA_CONF_DIR >> /var/log/upstart/herk.log
+riakstash_file=$MEGAMD_HOME_DIR/riakstash
 
 
 #test for existence of the riakstash file
 if [ -f $riakstash_file ]
 then
-  echo "if entry" >> /var/log/upstart/herk.log
+  echo "if entry" >> /var/log/megam/megamd/herk.log
   #read through the file
   while read line
   do
-    echo $line >> /var/log/upstart/herk.log
-    curl --connect-timeout 10 -X DELETE http://localhost:8098/riak/nodes/$line 
-   echo $? >> /var/log/upstart/herk.log
+    echo $line >> /var/log/megam/megamd/herk.log
+    curl --connect-timeout 10 -X DELETE http://localhost:8098/riak/nodes/$line
+    echo $? >> /var/log/megam/megamd/herk.log
     if [ $? == 0 ]; then
-        echo "*-----------------------------------------------------------------------*"  >> /var/log/upstart/herk.log 
-    	echo "cron herk_stash => deleted riak: $line" >> /var/log/upstart/herk.log
-        rm -r -f $MEGAM_AKKA_LOGS_DIR/$line	
-   	echo "cron herk_stash => deleted  log: $line" >> /var/log/upstart/herk.log
-        echo "*-----------------------------------------------------------------------*"  >> /var/log/upstart/herk.log
+      echo "*-----------------------------------------------------------------------*"  >> /var/log/upstart/herk.log
+    	echo "cron herk_stash => deleted riak: $line" >> /var/log/megam/megamd/herk.log
+      rm -r -f $MEGAMD_LOGS_DIR/$line
+   	  echo "cron herk_stash => deleted  log: $line" >> /var/log/megam/megamd/herk.log
+      echo "*-----------------------------------------------------------------------*"  >> /var/log/upstart/herk.log
     else
-     	echo "cron herk_stash => delete failed : $line" >> /var/log/upstart/herk.log	
+     	echo "cron herk_stash => delete failed : $line" >> /var/log/megam/megamd/herk.log
     fi
   done < $riakstash_file
-else 
-  echo "$riakstash_file not found"  >> /var/log/upstart/herk.log 
+else
+  echo "$riakstash_file not found"  >> /var/log/megam/megamd/herk.log
 fi
